#!/usr/bin/env bash
# Builds busybox 1.37.0 as a static x86-64 program against ferrousli: musl's
# headers, crt1.o and libferrousli.a, and nothing from the host's C library.
#
#     tools/busybox/build.sh            # from ferrousli/
#
# Sources are pinned, and refused if their checksums differ:
#   * busybox.net's busybox-1.37.0.tar.bz2, by the sha256 busybox.net publishes;
#   * Alpine's busyboxconfig at aports commit a8dcedab, by the sha512 in that
#     commit's APKBUILD. It is the config behind Alpine's busybox-static
#     1.37.0-r20, the musl busybox Ferrix's test-shell already runs, so the two
#     binaries differ in their C library and not in their applets.
#
# config.sh lists the changes made to that config, and why.
#
# Everything is downloaded to and built under $FERRIX_BUSYBOX, by default
# ~/.local/share/ferrix/busybox/ferrousli, never inside the repository. The
# binary is installed as $FERRIX_BUSYBOX/x86_64/busybox, only if it links.
#
# When the link fails, the symbols busybox needs and ferrousli does not yet
# have are written, sorted, to $FERRIX_BUSYBOX/undefined-symbols.txt, and the
# script exits 1. That list is ferrousli's plan for busybox.
set -euo pipefail

VERSION=1.37.0
TARBALL=busybox-$VERSION.tar.bz2
TARBALL_URL=https://busybox.net/downloads/$TARBALL
TARBALL_SHA256=3311dff32e746499f4df0d5df04d7eb396382d7e108bb9250e7b519b837043a4
APORTS_COMMIT=a8dcedab8fd001d8a35a703a70140fa071b3fa29
CONFIG_URL=https://gitlab.alpinelinux.org/alpine/aports/-/raw/$APORTS_COMMIT/main/busybox/busyboxconfig
CONFIG_SHA512=93f0fa512a394a07f760b13bd70a28424d3ad1a6c283b77fd4894114c5b472cfbe65f3441afa28596771d75527aaa9794706a3b329b4898e5d83bce799169929

here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ferrousli=$(cd "$here/../.." && pwd)
out=${FERRIX_BUSYBOX:-$HOME/.local/share/ferrix/busybox/ferrousli}
src=$out/src
build=$out/build
jobs=${JOBS:-4}

step() { printf '\n== %s\n' "$*"; }

fetch() { # url file checksum-command checksum
    local url=$1 file=$2 tool=$3 sum=$4
    if [ ! -f "$file" ]; then
        curl -fsSL --max-time 300 -o "$file.part" "$url"
        mv "$file.part" "$file"
    fi
    local got
    got=$("$tool" "$file" | cut -d' ' -f1)
    if [ "$got" != "$sum" ]; then
        echo "build.sh: $file does not match its pinned $tool" >&2
        echo "  expected $sum" >&2
        echo "  got      $got" >&2
        exit 1
    fi
}

step "sources"
mkdir -p "$src"
fetch "$TARBALL_URL" "$src/$TARBALL" sha256sum "$TARBALL_SHA256"
fetch "$CONFIG_URL" "$src/busyboxconfig" sha512sum "$CONFIG_SHA512"
echo "busybox $VERSION and Alpine's config at $APORTS_COMMIT, both verified"

step "ferrousli, release"
cargo build --release --lib --manifest-path "$ferrousli/Cargo.toml"
lib=$ferrousli/target/release/libferrousli.a
crt1=$(ls -t "$ferrousli"/target/release/build/ferrousli-*/out/crt1.o | head -1)
[ -f "$lib" ] && [ -f "$crt1" ]
echo "$lib"
echo "$crt1"

step "include directories"
# busybox includes the kernel's UAPI headers (<linux/*>, <asm/*>), which belong
# to no C library. The host's are used, from a directory holding only them, so
# that -nostdinc keeps the host's C headers out. musl's headers come first,
# the UAPI headers next, and the compiler's own directory last, for intrinsics
# only: every name musl's headers provide is found in them first.
uapi=$out/uapi
rm -rf "$uapi"
mkdir -p "$uapi"
for d in linux asm-generic mtd scsi sound video drm rdma misc; do
    [ -d "/usr/include/$d" ] && ln -s "/usr/include/$d" "$uapi/$d"
done
ln -s /usr/include/x86_64-linux-gnu/asm "$uapi/asm"
compiler_include=$(cc -print-file-name=include)

# Empty archives for the libraries busybox's link script asks for. ferrousli
# is one library, as musl is; these only stop the script refusing a library
# it cannot find before it has said what is undefined.
stubs=$out/stub-libs
mkdir -p "$stubs"
for l in m crypt resolv rt pthread dl util; do
    [ -f "$stubs/lib$l.a" ] || ar rc "$stubs/lib$l.a"
done

# The compiler busybox is built with: the host's cc, told where ferrousli is.
wrapper=$out/ferrousli-cc
cat > "$wrapper" <<EOF
#!/usr/bin/env bash
# Generated by ferrousli/tools/busybox/build.sh.
link=1
for a in "\$@"; do
    # -r links one directory's objects into a built-in.o. That is not a
    # program: giving it crt1.o puts a second _start in every binary the
    # object reaches, and the final link then fails on the duplicate.
    case "\$a" in -c|-S|-E|-M|-MM|-r) link=0 ;; esac
done
common=(-nostdinc -isystem "$ferrousli/include" -isystem "$uapi" -isystem "$compiler_include")
if [ \$link = 1 ]; then
    exec cc "\${common[@]}" -static -no-pie -nostdlib -L"$stubs" "$crt1" "\$@" "$lib"
else
    exec cc "\${common[@]}" "\$@"
fi
EOF
chmod +x "$wrapper"
echo "$wrapper"

step "unpack and configure"
rm -rf "$build"
mkdir -p "$build"
tar -xjf "$src/$TARBALL" -C "$build" --strip-components=1
cp "$src/busyboxconfig" "$build/.config"
# shellcheck source=config.sh
. "$here/config.sh"
apply_config_changes "$build/.config"
make -C "$build" CC="$wrapper" HOSTCC=cc oldconfig </dev/null > "$out/oldconfig.log" 2>&1
grep -E '^CONFIG_(STATIC|PIE)=|^# CONFIG_(STATIC|PIE) is not set' "$build/.config"

step "build"
set +e
make -C "$build" -j"$jobs" CC="$wrapper" HOSTCC=cc V=1 busybox > "$out/build.log" 2>&1
status=$?
set -e
echo "make exited $status; log in $out/build.log"

step "undefined symbols"
# busybox's scripts/trylink keeps the failed link's output in
# busybox_unstripped.out rather than in make's log, so read both.
cat "$out/build.log" "$build/busybox_unstripped.out" 2>/dev/null \
    | grep -oE "undefined reference to \`[^']+'" \
    | sed -E "s/undefined reference to \`([^']+)'/\1/" \
    | sort -u > "$out/undefined-symbols.txt" || true
[ -f "$build/busybox_unstripped.out" ] && cp "$build/busybox_unstripped.out" "$out/link.log"
count=$(wc -l < "$out/undefined-symbols.txt")
echo "$count undefined: $out/undefined-symbols.txt"

if [ "$status" -ne 0 ]; then
    if [ "$count" -eq 0 ]; then
        echo "build.sh: the build failed before linking; the end of the log:" >&2
        grep -E 'error|Error' "$out/build.log" | head -30 >&2
    fi
    exit 1
fi

step "install"
mkdir -p "$out/x86_64"
install -m 755 "$build/busybox" "$out/x86_64/busybox"
file "$out/x86_64/busybox"
echo "$out/x86_64/busybox"
