# What every port under tools/ports/ shares, sourced by each build.sh:
# pinned downloads, ferrousli's release library, and the compilers that build
# a program against it and nothing else.
#
# A port builds a static x86-64 program with the host's gcc, against musl's
# headers in include/, crt1.o and libferrousli.a, the way
# tools/busybox/build.sh builds busybox. It downloads and builds under
# $FERRIX_PORTS, by default ~/.local/share/ferrix/ports/ferrousli, never inside
# the repository, and installs into $FERRIX_PORTS/x86_64 only once it links.
# When a link fails, the symbols ferrousli does not have yet are written to
# $FERRIX_PORTS/<port>/undefined-symbols.txt and the build exits 1.

here_ports=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ferrousli=$(cd "$here_ports/../.." && pwd)
ports=${FERRIX_PORTS:-$HOME/.local/share/ferrix/ports/ferrousli}
prefix=$ports/x86_64
jobs=${JOBS:-$(nproc)}

step() { printf '\n== %s\n' "$*"; }
fail() {
    echo "${0##*/}: $*" >&2
    exit 1
}

fetch() { # url file checksum-command checksum
    local url=$1 file=$2 tool=$3 sum=$4
    if [ ! -f "$file" ]; then
        curl -fsSL --max-time 900 -o "$file.part" "$url"
        mv "$file.part" "$file"
    fi
    local got
    got=$("$tool" "$file" | cut -d' ' -f1)
    if [ "$got" != "$sum" ]; then
        echo "${0##*/}: $file does not match its pinned $tool" >&2
        echo "  expected $sum" >&2
        echo "  got      $got" >&2
        exit 1
    fi
}

# Build ferrousli in the release profile and set $lib and $crt1.
build_ferrousli() {
    step "ferrousli, release"
    local target=${CARGO_TARGET_DIR:-$ferrousli/target}
    cargo build --release --lib --manifest-path "$ferrousli/Cargo.toml"
    lib=$target/release/libferrousli.a
    crt1=$(ls -t "$target"/release/build/ferrousli-*/out/crt1.o | head -1)
    [ -f "$lib" ] && [ -f "$crt1" ] || fail "cargo built no libferrousli.a and crt1.o"
    echo "$lib"
    echo "$crt1"
}

# Write $ports/bin/ferrousli-cc, ferrousli-c++ and ferrousli-c++-bare, which
# compile against ferrousli's headers and link against crt1.o and
# libferrousli.a, set $CC, $CXX and $CXX_BARE to them, and put them on PATH.
# Needs build_ferrousli first.
#
# The kernel's UAPI headers (<linux/*>, <asm/*>) belong to no C library; the
# host's are used from a directory holding only them, as busybox's build does,
# so that -nostdinc keeps the host's C headers out. musl's headers come first,
# then the UAPI headers, then the compiler's own directory, for intrinsics
# only.
#
# The C++ compiler adds $prefix/include/c++/v1, where tools/ports/libcxx
# installs libc++'s headers, ahead of all of them, and links libc++,
# libc++abi and libunwind from $prefix/lib. It is usable once that port is
# built. The bare C++ compiler has no C++ library at all, for building that
# port. Both link with --eh-frame-hdr, which gcc leaves out of a static link:
# libunwind finds a program's unwind tables through the header it makes. And
# both link gcc's crtbeginT.o and crtend.o, as gcc's own static link does:
# they define __dso_handle, which every C++ static destructor is registered
# against, and which belongs to the compiler rather than to a C library.
#
# What the wrappers add after the caller's arguments comes after `-x none`, so
# a caller that compiles from standard input with `-x c++ -` does not make gcc
# read crtend.o and the libraries as C++ source.
#
# Empty libm, libpthread and the rest stand in for the libraries a configure
# script asks for by name: ferrousli is one library, as musl is.
make_compilers() {
    step "compilers"
    local bin=$ports/bin uapi=$ports/uapi stubs=$ports/stub-libs
    mkdir -p "$bin" "$stubs"
    rm -rf "$uapi"
    mkdir -p "$uapi"
    local d
    for d in linux asm-generic mtd scsi sound video drm rdma misc; do
        [ -d "/usr/include/$d" ] && ln -s "/usr/include/$d" "$uapi/$d"
    done
    ln -s /usr/include/x86_64-linux-gnu/asm "$uapi/asm"
    local l
    for l in m crypt resolv rt pthread dl util; do
        [ -f "$stubs/lib$l.a" ] || ar rc "$stubs/lib$l.a"
    done
    local compiler_include crtbegin crtend
    compiler_include=$(gcc -print-file-name=include)
    crtbegin=$(gcc -print-file-name=crtbeginT.o)
    crtend=$(gcc -print-file-name=crtend.o)

    local name driver kind
    for name in ferrousli-cc ferrousli-c++ ferrousli-c++-bare; do
        case $name in
            ferrousli-cc) driver=gcc kind=c ;;
            ferrousli-c++) driver=g++ kind=c++ ;;
            ferrousli-c++-bare) driver=g++ kind=bare ;;
        esac
        cat > "$bin/$name" <<EOF
#!/usr/bin/env bash
# Generated by ferrousli/tools/ports/common.sh.
link=1
for a in "\$@"; do
    case "\$a" in -c|-S|-E|-M|-MM|-r|-print-*|--version|-v|-dumpversion|-dumpmachine) link=0 ;; esac
done
common=(-nostdinc -isystem "$ferrousli/include" -isystem "$uapi" -isystem "$compiler_include")
cxx=()
cxxlibs=()
case $kind in
    c++)
        cxx=(-nostdinc++ -isystem "$prefix/include/c++/v1")
        cxxlibs=(-Wl,--eh-frame-hdr -L"$prefix/lib" -lc++ -lc++abi -lunwind)
        ;;
    bare)
        cxx=(-nostdinc++)
        cxxlibs=(-Wl,--eh-frame-hdr)
        ;;
esac
begin=()
end=()
if [ $kind != c ]; then
    begin=("$crtbegin")
    end=("$crtend")
fi
if [ \$link = 1 ]; then
    exec $driver "\${cxx[@]}" "\${common[@]}" -static -no-pie -nostdlib -L"$stubs" -L"$prefix/lib" \\
        "$crt1" "\${begin[@]}" "\$@" -x none "\${cxxlibs[@]}" -Wl,--start-group "$lib" -lgcc -Wl,--end-group "\${end[@]}"
else
    exec $driver "\${cxx[@]}" "\${common[@]}" "\$@"
fi
EOF
        chmod +x "$bin/$name"
    done
    export PATH=$bin:$PATH
    CC=$bin/ferrousli-cc
    CXX=$bin/ferrousli-c++
    CXX_BARE=$bin/ferrousli-c++-bare
    echo "$CC"
    echo "$CXX"
    echo "$CXX_BARE"
}

# Write the symbols a failed link left undefined, from the logs given, to
# $1 and say how many there are.
undefined_symbols() { # list log...
    local list=$1
    shift
    cat "$@" 2>/dev/null \
        | grep -oE "undefined reference to \`[^']+'" \
        | sed -E "s/undefined reference to \`([^']+)'/\1/" \
        | sort -u > "$list" || true
    echo "$(wc -l < "$list") undefined: $list"
}
