#!/usr/bin/env bash
# Builds sshdt 0.4.2, an SSH server written in Rust, as a static x86-64
# program against ferrousli: Rust's own `std` and unwinder for the musl
# target, and libferrousli.a in the C library's place, as
# tools/uutils/build.sh builds uutils.
#
#     tools/ports/sshdt/build.sh           # from ferrousli/
#
# Installs, under $FERRIX_PORTS (see ../common.sh):
#   x86_64/bin/sshdt
#
# Pinned, and refused if its checksum differs: crates.io's package of 0.4.2,
# by the sha256 crates.io itself publishes for it. The package carries its own
# Cargo.lock and the build passes --locked, so every crate under it is pinned
# by sshdt and checked by cargo against crates.io's checksum.
#
# Why sshdt: it is a whole daemon rather than a library -- russh underneath,
# a PTY for interactive sessions, exec, SFTP and scp -- and it asks nothing of
# the system beyond sockets, epoll and a PTY. The alternatives either were a
# library with no server (russh, sunset) or sandbox themselves with seccomp
# and Landlock (narrowd), which Ferrix does not have. What it does not do is
# change user: every session runs as whoever started it.
#
# Its one C dependency is aws-lc, under russh's cryptography. It is compiled
# with ferrousli-cc, against musl's headers, so what it calls is what
# ferrousli provides and not the build host's glibc.
set -euo pipefail

here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=../common.sh
. "$here/../common.sh"

SSHDT_VERSION=0.4.2
SSHDT_TARBALL=sshdt-$SSHDT_VERSION.crate
SSHDT_URL=https://static.crates.io/crates/sshdt/$SSHDT_TARBALL
SSHDT_SHA256=ae571e2d5a269920dc99503dc084c61d3917471654041db5a20f241be6e63d78

# The musl target, for the reason tools/uutils/sources.sh gives: ferrousli
# links the gnu target too, but only the musl one lets a static Rust program
# find out about itself through the C library rather than through /proc.
TARGET=x86_64-unknown-linux-musl

work=$ports/sshdt
src=$ports/src

# The toolchain Ferrix pins, named outright: the crate is built outside the
# repository, where rustup would otherwise pick the machine's default.
toolchain=$(sed -n 's/^channel *= *"\(.*\)"/\1/p' "$ferrousli/../rust-toolchain.toml")
[ -n "$toolchain" ] || fail "no channel in rust-toolchain.toml"
export RUSTUP_TOOLCHAIN=$toolchain
echo "toolchain $toolchain"

step "sources"
mkdir -p "$src" "$work"
fetch "$SSHDT_URL" "$src/$SSHDT_TARBALL" sha256sum "$SSHDT_SHA256"
echo "sshdt $SSHDT_VERSION, verified"

build_ferrousli
make_compilers

step "the panic handler, weakened"
# ferrousli's #[panic_handler] and std's are both `rust_begin_unwind`; the
# copy this program links has ferrousli's made weak, so std's wins. The same
# step, with its reasoning, is in tools/uutils/build.sh.
lib_weak=$work/libferrousli-weak.a
cp "$lib" "$lib_weak"
panic_symbol=$(nm --defined-only "$lib" 2>/dev/null |
    awk '$2 == "T" && $3 ~ /rust_begin_unwind/ { print $3 }' | sed -n 1p)
[ -n "$panic_symbol" ] || fail "no rust_begin_unwind in $lib; has the panic handler moved?"
objcopy --weaken-symbol="$panic_symbol" "$lib_weak"
echo "weakened $panic_symbol"

step "link libraries"
# Empty stand-ins for the libraries rustc names, and rustc's own libunwind,
# copied so that musl's libc.a beside it cannot satisfy -lc.
libs=$work/link-libs
rm -rf "$libs"
mkdir -p "$libs"
for l in c m rt pthread dl util gcc_s; do
    ar rc "$libs/lib$l.a"
done
selfcontained=$(rustc --print sysroot)/lib/rustlib/$TARGET/lib/self-contained
[ -f "$selfcontained/libunwind.a" ] ||
    fail "no libunwind.a in $selfcontained; run: rustup target add $TARGET"
cp "$selfcontained/libunwind.a" "$libs/libunwind.a"

step "linker wrapper"
wrapper=$work/ferrousli-link
cat > "$wrapper" <<EOF
#!/usr/bin/env bash
# Generated by ferrousli/tools/ports/sshdt/build.sh.
args=()
for a in "\$@"; do
    case "\$a" in -fuse-ld=*) ;; *) args+=("\$a") ;; esac
done
exec cc -static -no-pie -nostdlib -L"$libs" "$crt1" "\${args[@]}" -Wl,--start-group "$lib_weak" -lgcc -Wl,--end-group
EOF
chmod +x "$wrapper"

step "build"
build=$work/build
rm -rf "$build"
mkdir -p "$build"
tar -xzf "$src/$SSHDT_TARBALL" -C "$build" --strip-components=1
# The crate's rust-toolchain.toml names an older compiler than Ferrix's; the
# one exported above is the one meant, and the file would override it.
rm -f "$build/rust-toolchain.toml"
set +e
(
    cd "$build" || exit 1
    CC_x86_64_unknown_linux_musl=$CC \
    CXX_x86_64_unknown_linux_musl=$CXX_BARE \
    AR_x86_64_unknown_linux_musl=ar \
    CARGO_TARGET_DIR=$work/target \
    RUSTFLAGS="-C target-feature=+crt-static -C link-self-contained=no -C linker=$wrapper -C relocation-model=static" \
        cargo build --release --locked --target "$TARGET" --bin sshdt
) > "$work/build.log" 2>&1
status=$?
set -e
echo "cargo exited $status; log in $work/build.log"
undefined_symbols "$work/undefined-symbols.txt" "$work/build.log"
if [ "$status" -ne 0 ]; then
    grep -E '^(error|warning: aws)' "$work/build.log" | sort -u | head -30 >&2
    exit 1
fi

step "install"
mkdir -p "$prefix/bin"
install -m 755 -s "$work/target/$TARGET/release/sshdt" "$prefix/bin/sshdt"
ls -l "$prefix/bin/sshdt"
