#!/usr/bin/env bash
# Builds uutils/coreutils as one static x86-64 multicall program against
# ferrousli: Rust's own `std` and unwinder for the musl target, and
# libferrousli.a in the C library's place.
#
#     tools/uutils/build.sh            # from ferrousli/
#
# sources.sh pins the release and names the target and the feature set, each
# with its reason. On Windows, build-windows.sh builds the same program from
# the same sources without a C toolchain.
#
# Everything is downloaded to and built under $FERRIX_UUTILS, by default
# ~/.local/share/ferrix/uutils/ferrousli, never inside the repository. The
# binary is installed as $FERRIX_UUTILS/x86_64/coreutils, only if it links.
#
# When the link fails, the symbols uutils needs and ferrousli does not have
# are written, sorted, to $FERRIX_UUTILS/undefined-symbols.txt and the script
# exits 1, as tools/busybox/build.sh does for busybox.
set -euo pipefail

here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ferrousli=$(cd "$here/../.." && pwd)
out=${FERRIX_UUTILS:-$HOME/.local/share/ferrix/uutils/ferrousli}
src=$out/src
build=$out/build

step() { printf '\n== %s\n' "$*"; }
fail() {
    echo "${0##*/}: $*" >&2
    exit 1
}

# The toolchain Ferrix pins, named outright. uutils is unpacked and built
# outside the repository, where rustup would otherwise fall back to the
# machine's default toolchain -- which is usually older than ferrousli's
# rust-version and has no musl target installed.
toolchain=$(sed -n 's/^channel *= *"\(.*\)"/\1/p' "$ferrousli/../rust-toolchain.toml")
[ -n "$toolchain" ] || fail "no channel in rust-toolchain.toml"
export RUSTUP_TOOLCHAIN=$toolchain
echo "toolchain $toolchain"

# shellcheck source=sources.sh
. "$here/sources.sh"

step "sources"
fetch_sources "$src"

step "ferrousli, release"
# Where cargo puts the library: the caller's CARGO_TARGET_DIR when set.
target=${CARGO_TARGET_DIR:-$ferrousli/target}
cargo build --release --lib --manifest-path "$ferrousli/Cargo.toml"
lib=$target/release/libferrousli.a
crt1=$(ls -t "$target"/release/build/ferrousli-*/out/crt1.o | head -1)
[ -f "$lib" ] && [ -f "$crt1" ] || fail "cargo built no libferrousli.a and crt1.o"
echo "$lib"
echo "$crt1"

step "link libraries"
# Empty archives for the libraries rustc names on its linker line. ferrousli
# is one library, as musl is; these only stop the linker refusing a library it
# cannot find before it has said what is undefined.
libs=$out/link-libs
rm -rf "$libs"
mkdir -p "$libs"
for l in c m rt pthread dl util gcc_s; do
    ar rc "$libs/lib$l.a"
done
# -lunwind is not one of those. The musl target names it where the gnu target
# names -lgcc_eh, `std`'s panic machinery really calls into it, and rustc
# ships the answer: self-contained/libunwind.a, beside the musl libc.a this
# build does not want. It is copied rather than reached with -L, so that the
# linker cannot find musl's libc.a next to it and satisfy -lc from there.
selfcontained=$(rustc --print sysroot)/lib/rustlib/$TARGET/lib/self-contained
[ -f "$selfcontained/libunwind.a" ] ||
    fail "no libunwind.a in $selfcontained; run: rustup target add $TARGET"
cp "$selfcontained/libunwind.a" "$libs/libunwind.a"

step "linker wrapper"
# The linker uutils is linked with: the host's cc, told to use ferrousli's
# entry object and library and nothing of its own.
wrapper=$out/ferrousli-link
cat > "$wrapper" <<EOF
#!/usr/bin/env bash
# Generated by ferrousli/tools/uutils/build.sh.
# rustc asks cc for lld, which a host gcc has no driver for, and which linker
# does the work is not this build's concern.
args=()
for a in "\$@"; do
    case "\$a" in -fuse-ld=*) ;; *) args+=("\$a") ;; esac
done
exec cc -static -no-pie -nostdlib -L"$libs" "$crt1" "\${args[@]}" "$lib"
EOF
chmod +x "$wrapper"
cat "$wrapper"

step "unpack"
rm -rf "$build"
mkdir -p "$build"
tar -xzf "$src/$TARBALL" -C "$build" --strip-components=1

step "build"
set +e
(
    cd "$build" || exit 1
    # onig_sys, the one C dependency in the tree, is compiled with the host's
    # cc against the host's headers. Its object only has to link, and what it
    # calls -- including glibc's fortified __memcpy_chk -- ferrousli has.
    CC_x86_64_unknown_linux_musl=cc \
    AR_x86_64_unknown_linux_musl=ar \
    CARGO_TARGET_DIR=$build/target \
    RUSTFLAGS="-C target-feature=+crt-static -C link-self-contained=no -C linker=$wrapper -C relocation-model=static" \
        cargo build --release --locked --target "$TARGET" \
        --no-default-features --features "$FEATURES" --bin coreutils
) > "$out/build.log" 2>&1
status=$?
set -e
echo "cargo exited $status; log in $out/build.log"

step "undefined symbols"
grep -oE "undefined reference to \`[^']+'" "$out/build.log" |
    sed -E "s/undefined reference to .([^']+)'/\1/" |
    sort -u > "$out/undefined-symbols.txt" || true
count=$(wc -l < "$out/undefined-symbols.txt")
echo "$count undefined: $out/undefined-symbols.txt"

if [ "$status" -ne 0 ]; then
    if [ "$count" -eq 0 ]; then
        echo "build.sh: the build failed before linking; the errors:" >&2
        grep -E '^error' "$out/build.log" | head -30 >&2
    fi
    exit 1
fi

step "install"
mkdir -p "$out/x86_64"
install -m 755 "$build/target/$TARGET/release/coreutils" "$out/x86_64/coreutils"
file "$out/x86_64/coreutils"
echo "$out/x86_64/coreutils"
