#!/usr/bin/env python3
"""Generate ferrousli's Unicode tables from musl's.

    python3 tools/gen-unicode.py          # write src/generated/unicode.rs
    python3 tools/gen-unicode.py --check  # fail if it is stale
    python3 tools/gen-unicode.py --musl PATH

musl (MIT) generates compact tables from the Unicode Character Database for
iswalpha, iswpunct, wcwidth and case mapping, and keeps the output in
src/ctype/*.h. Those tables, from musl 1.2.5, are Unicode 12.1.0. This script
converts them to Rust unchanged, number for number, so that the functions
reading them can follow musl's lookups exactly. It does not reinterpret them.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "generated" / "unicode.rs"
MUSL = pathlib.Path.home() / ".local/share/ferrix/ferrousli-ref/musl-1.2.5"

NUMBER = re.compile(r"-?(?:0x[0-9a-fA-F]+|\d+)")

# The bit tables: each is a list of byte values and nothing else.
BIT_TABLES = (
    ("ALPHA", "alpha.h", "`iswalpha`: letters, and the other Alphabetic characters"),
    ("PUNCT", "punct.h", "`iswpunct`: punctuation and symbols"),
    ("NONSPACING", "nonspacing.h", "`wcwidth`: characters of width zero"),
    ("WIDE", "wide.h", "`wcwidth`: characters of width two"),
)


def numbers(text: str) -> list[int]:
    return [int(n, 0) for n in NUMBER.findall(text)]


def c_array(source: str, name: str) -> str:
    """The initialiser of the C array `name` in `source`."""
    match = re.search(
        r"static const [a-z ]+ " + re.escape(name) + r"\[\](?:\[2\])? = \{(.*?)\n\};",
        source,
        re.S,
    )
    if not match:
        sys.exit(f"gen-unicode: no array {name} in casemap.h")
    return match.group(1)


def rows(values: list[str], per_row: int) -> str:
    lines = []
    for start in range(0, len(values), per_row):
        lines.append("    " + ", ".join(values[start : start + per_row]) + ",")
    return "\n".join(lines)


def generate(musl: pathlib.Path) -> str:
    ctype = musl / "src" / "ctype"
    out = [
        f"// Generated by tools/gen-unicode.py from musl 1.2.5's src/ctype/*.h "
        "(MIT, Copyright © 2005-2020 Rich Felker, et al.). Do not edit.",
        "",
    ]
    for name, file, what in BIT_TABLES:
        values = numbers((ctype / file).read_text())
        if any(v < 0 or v > 255 for v in values):
            sys.exit(f"gen-unicode: {file} holds a value that is not a byte")
        out.append(f"/// musl's `{file}`, the two-level bit table for {what}.")
        out.append(f"static {name}: [u8; {len(values)}] = [")
        out.append(rows([str(v) for v in values], 20))
        out.append("];")
        out.append("")

    casemap = (ctype / "casemap.h").read_text()
    tab = numbers(c_array(casemap, "tab"))
    rules = numbers(c_array(casemap, "rules"))
    bases = numbers(c_array(casemap, "rulebases"))
    exceptions = numbers(c_array(casemap, "exceptions"))
    if len(bases) != 512 or len(exceptions) % 2:
        sys.exit("gen-unicode: casemap.h does not have the shape expected")

    out.append("/// musl's `casemap.h` `tab`: the two-level base-6 table of rule indices.")
    out.append(f"static CASE_TAB: [u8; {len(tab)}] = [")
    out.append(rows([str(v) for v in tab], 20))
    out.append("];")
    out.append("")
    out.append("/// musl's `casemap.h` `rules`: a rule type in the low byte, and a delta")
    out.append("/// or an exception range above it.")
    out.append(f"static CASE_RULES: [i32; {len(rules)}] = [")
    out.append(rows([hex(v) if v >= 0 else "-" + hex(-v) for v in rules], 8))
    out.append("];")
    out.append("")
    out.append("/// musl's `casemap.h` `rulebases`: where each 256-character block's rules")
    out.append("/// start.")
    out.append("static CASE_RULE_BASES: [u8; 512] = [")
    out.append(rows([str(v) for v in bases], 20))
    out.append("];")
    out.append("")
    out.append("/// musl's `casemap.h` `exceptions`: a character's low byte and its rule,")
    out.append("/// sorted within each block.")
    out.append(f"static CASE_EXCEPTIONS: [[u8; 2]; {len(exceptions) // 2}] = [")
    pairs = [f"[{exceptions[i]}, {exceptions[i + 1]}]" for i in range(0, len(exceptions), 2)]
    out.append(rows(pairs, 8))
    out.append("];")
    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the output is stale")
    parser.add_argument("--musl", type=pathlib.Path, default=MUSL, help="musl 1.2.5's source")
    args = parser.parse_args()

    text = generate(args.musl)
    if args.check:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"gen-unicode: {OUT} is stale; run tools/gen-unicode.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
