#!/usr/bin/env python3
"""Generate ferrousli's system call numbers and errno values from Linux's headers.

    python3 tools/gen-abi.py          # write src/generated/
    python3 tools/gen-abi.py --check  # fail if src/generated/ is stale or wrong

A system call number written from memory dispatches to the wrong call, and
nothing reports it. So every number here is read from the kernel's UAPI
headers. The generated Rust is then parsed a second, independent way, and each
constant is looked up in the header again.

To use a new system call, add its name to SYSCALLS and run this.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "generated"

UNISTD = pathlib.Path("/usr/include/x86_64-linux-gnu/asm/unistd_64.h")
ERRNO_HEADERS = (
    pathlib.Path("/usr/include/asm-generic/errno-base.h"),
    pathlib.Path("/usr/include/asm-generic/errno.h"),
)
# The aliases C programs use. The headers define a few more for the kernel's
# own use, which a C library does not export.
ERRNO_ALIASES = ("EWOULDBLOCK", "EDEADLOCK")

SYSCALLS = """
read write open close stat fstat lstat poll lseek mmap mprotect munmap brk
rt_sigaction rt_sigprocmask rt_sigreturn ioctl pread64 pwrite64 readv writev
access pipe sched_yield mremap msync madvise dup dup2 pause nanosleep
getitimer alarm setitimer getpid clone fork vfork execve exit wait4 kill uname
fcntl flock fsync fdatasync truncate ftruncate getcwd chdir fchdir rename
mkdir rmdir creat link unlink symlink readlink chmod fchmod chown fchown
lchown umask gettimeofday getrlimit getrusage sysinfo times getuid getgid
setuid setgid geteuid getegid setpgid getppid getpgrp setsid setreuid
setregid getgroups setgroups getpgid getsid rt_sigpending rt_sigtimedwait
rt_sigqueueinfo rt_sigsuspend sigaltstack statfs fstatfs setrlimit sync
arch_prctl gettid tkill futex sched_getaffinity getdents64 set_tid_address
clock_settime clock_gettime clock_getres clock_nanosleep exit_group tgkill
openat mkdirat fchownat newfstatat unlinkat renameat linkat symlinkat
readlinkat fchmodat faccessat pselect6 ppoll utimensat dup3 pipe2 prlimit64
renameat2 getrandom memfd_create execveat statx clone3 faccessat2
fadvise64 fallocate mlock munlock mlockall munlockall getpriority setpriority
waitid preadv pwritev mknodat setresuid setresgid fchmodat2
set_robust_list get_robust_list sched_setparam sched_getparam
sched_setscheduler sched_getscheduler sched_get_priority_max
sched_get_priority_min sched_rr_get_interval sched_setaffinity getcpu prctl
rt_tgsigqueueinfo mount umount2 pivot_root chroot swapon swapoff syncfs readahead
socket connect accept accept4 sendto recvfrom sendmsg recvmsg shutdown bind
listen getsockname getpeername socketpair setsockopt getsockopt sendfile
shmget shmat shmctl shmdt semget semop semctl semtimedop msgget msgsnd msgrcv
msgctl capget capset personality setns unshare sethostname setdomainname
reboot syslog clock_adjtime settimeofday inotify_init1 inotify_add_watch
inotify_rm_watch getresuid getresgid
""".split()

DEFINE_SYSCALL = re.compile(r"^#define __NR_(\w+) (\d+)$", re.M)
DEFINE_ERRNO = re.compile(
    r"^#define\s+(E[A-Z0-9]+)\s+(\d+)\s*(?:/\*\s*(.*?)\s*\*/)?\s*$", re.M
)
DEFINE_ALIAS = re.compile(r"^#define\s+(E[A-Z0-9]+)\s+(E[A-Z0-9]+)\b", re.M)


def syscalls() -> list[tuple[str, int]]:
    if len(set(SYSCALLS)) != len(SYSCALLS):
        sys.exit("gen-abi: a system call is listed twice")
    numbers = dict(DEFINE_SYSCALL.findall(UNISTD.read_text()))
    missing = [name for name in SYSCALLS if name not in numbers]
    if missing:
        sys.exit(f"gen-abi: not in {UNISTD}: {' '.join(missing)}")
    return [(name, int(numbers[name])) for name in SYSCALLS]


def render_nr(table: list[tuple[str, int]]) -> str:
    lines = [f"// Generated by tools/gen-abi.py from {UNISTD}. Do not edit.", ""]
    for name, number in table:
        lines.append(f"/// `{name}`.")
        lines.append(f"pub const {name.upper()}: usize = {number};")
    return "\n".join(lines) + "\n"


def errnos() -> tuple[list[tuple[str, int, str]], list[tuple[str, str]]]:
    values: list[tuple[str, int, str]] = []
    aliases: list[tuple[str, str]] = []
    for header in ERRNO_HEADERS:
        text = header.read_text()
        values += [(m[1], int(m[2]), m[3] or "") for m in DEFINE_ERRNO.finditer(text)]
        aliases += [
            (m[1], m[2]) for m in DEFINE_ALIAS.finditer(text) if m[1] in ERRNO_ALIASES
        ]
    return values, aliases


def render_errno(values: list[tuple[str, int, str]], aliases: list[tuple[str, str]]) -> str:
    sources = " and ".join(str(header) for header in ERRNO_HEADERS)
    lines = [f"// Generated by tools/gen-abi.py from {sources}. Do not edit.", ""]
    for name, value, comment in values:
        text = comment.rstrip(".")
        lines.append(f"/// `{name}`: {text}." if text else f"/// `{name}`.")
        lines.append(f"pub const {name}: c_int = {value};")
    for name, target in aliases:
        lines.append(f"/// `{name}`: the same as [`{target}`].")
        lines.append(f"pub const {name}: c_int = {target};")
    return "\n".join(lines) + "\n"


def check_back(nr_text: str, errno_text: str) -> list[str]:
    """Parse the generated Rust and look every constant up in the headers."""
    problems = []
    unistd = UNISTD.read_text()
    for name, value in re.findall(r"pub const ([A-Z0-9_]+): usize = (\d+);", nr_text):
        if not re.search(rf"^#define __NR_{name.lower()} {value}$", unistd, re.M):
            problems.append(f"nr::{name} = {value} is not in {UNISTD}")
    headers = "\n".join(header.read_text() for header in ERRNO_HEADERS)
    for name, value in re.findall(r"pub const (E[A-Z0-9]+): c_int = (\d+);", errno_text):
        if not re.search(rf"^#define\s+{name}\s+{value}\b", headers, re.M):
            problems.append(f"{name} = {value} is not in the errno headers")
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check", action="store_true", help="fail if src/generated/ is stale or wrong"
    )
    args = parser.parse_args()

    nr_text = render_nr(syscalls())
    errno_text = render_errno(*errnos())
    files = {OUT / "nr.rs": nr_text, OUT / "errno.rs": errno_text}

    problems = check_back(nr_text, errno_text)
    if args.check:
        for path, text in files.items():
            if not path.exists() or path.read_text() != text:
                problems.append(f"{path.relative_to(ROOT)} is stale: run tools/gen-abi.py")
    elif not problems:
        OUT.mkdir(exist_ok=True)
        for path, text in files.items():
            path.write_text(text)

    for problem in problems:
        print(f"gen-abi: {problem}", file=sys.stderr)
    if not problems:
        print(f"gen-abi: {len(SYSCALLS)} system calls, {errno_text.count('pub const')} errno values")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
