#!/usr/bin/env python3
"""Record which version glibc gives each of its symbols, for one architecture.

A program linked against glibc asks for `printf@GLIBC_2.2.5`, not `printf`:
the version is part of the name it binds to. For `libferrousli.so` to stand
in glibc's place it has to define each symbol at the version glibc's own
libraries give it by default -- the `@@` one, which is what every program
linked since that version asks for.

This reads that from a glibc installation with binutils' `readelf`, and
writes `tools/glibc-versions/<arch>.txt`: one `name VERSION` line per
default-version symbol of the libraries ferrousli stands in for, sorted. It
records names and version strings only, the interface glibc publishes, and
nothing of glibc's code. `tools/build-shared.sh` turns it into the version
script the shared library is linked with.

Usage: gen-glibc-versions.py <arch> <directory holding libc.so.6 and the rest>
       gen-glibc-versions.py <arch> <directory> --check
"""

import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "tools" / "glibc-versions"

# glibc's libraries whose names ferrousli's one library answers to.
LIBRARIES = (
    "libc.so.6",
    "libm.so.6",
    "libresolv.so.2",
    "libpthread.so.0",
    "libdl.so.2",
    "librt.so.1",
    "libutil.so.1",
    "libanl.so.1",
)

ARCHES = ("x86_64", "aarch64", "armv7a")

# A dynamic symbol line: `Num: Value Size Type Bind Vis Ndx Name@@VERSION`.
DEFINED = re.compile(r"^\s*\d+:\s+\S+\s+\S+\s+\S+\s+(GLOBAL|WEAK)\s+\S+\s+(?!UND)\S+\s+(\S+?)@@(\S+)")


def table(directory: pathlib.Path) -> dict[str, str]:
    versions: dict[str, str] = {}
    for library in LIBRARIES:
        path = directory / library
        if not path.exists():
            continue
        out = subprocess.run(
            ["readelf", "--dyn-syms", "-W", str(path)],
            check=True,
            capture_output=True,
            text=True,
            env={"LC_ALL": "C", "PATH": "/usr/bin:/bin"},
        ).stdout
        for line in out.splitlines():
            found = DEFINED.match(line)
            if not found:
                continue
            name, version = found.group(2), found.group(3)
            # A name is in one library; `libc.so.6`, read first, wins if two
            # ever disagree.
            versions.setdefault(name, version)
    if "libc.so.6" not in {p.name for p in directory.iterdir()}:
        sys.exit(f"gen-glibc-versions: no libc.so.6 in {directory}")
    return versions


def render(arch: str, versions: dict[str, str]) -> str:
    lines = [
        f"# Generated by tools/gen-glibc-versions.py for {arch}. Do not edit.",
        "# Each symbol glibc's libraries define, and the version they define it",
        "# at by default: the version a program linked against glibc asks for.",
    ]
    lines += [f"{name} {version}" for name, version in sorted(versions.items())]
    return "\n".join(lines) + "\n"


def main() -> int:
    args = sys.argv[1:]
    check = "--check" in args
    args = [a for a in args if a != "--check"]
    if len(args) != 2 or args[0] not in ARCHES:
        sys.exit(__doc__)
    arch, directory = args[0], pathlib.Path(args[1])
    text = render(arch, table(directory))
    path = OUT / f"{arch}.txt"
    if check:
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            print(f"gen-glibc-versions: {path.relative_to(ROOT).as_posix()} is out of date")
            return 1
        return 0
    OUT.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    print(f"gen-glibc-versions: {len(text.splitlines()) - 3} symbols for {arch}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
