//! Names ARMv7-A's programs call that are another name here: musl's 64-bit
//! time functions, and the `long double` functions.
//!
//! musl's headers for a 32-bit target redirect every function that takes a
//! `time_t`, a `struct timespec` or a `struct stat` to a name of its own, such
//! as `stat` to `__stat_time64`, so that a program built for 64-bit time never
//! calls the old 32-bit function of the same name. This library's `time_t` is
//! 64 bits everywhere, so each such name is simply the function itself.
//!
//! On ARMv7-A a `long double` is a `double`, and passed and returned as one,
//! so `sqrtl` is `sqrt`. `nexttoward` and `nexttowardl` take a `double` second
//! argument there, which makes them `nextafter`; `nexttowardf`, whose first is
//! a `float`, is not `nextafterf` and is written out in `math::arm`.
//!
//! Each name is a branch to the function, which rustc may put in any codegen
//! unit, rather than a `.set` alias, which the assembler would have to see
//! the definition of. The first list is every `__REDIR` in `include/` whose
//! function this library has; the C tests, built against those headers, call
//! through it.

#[cfg(not(test))]
core::arch::global_asm!(
    ".pushsection .text.ferrousli_arm_names,\"ax\",%progbits",
    ".p2align 2",
    ".arm",
    ".globl __adjtimex_time64",
    ".type __adjtimex_time64, %function",
    "__adjtimex_time64:",
    "b adjtimex",
    ".globl __clock_adjtime64",
    ".type __clock_adjtime64, %function",
    "__clock_adjtime64:",
    "b clock_adjtime",
    ".globl __clock_getres_time64",
    ".type __clock_getres_time64, %function",
    "__clock_getres_time64:",
    "b clock_getres",
    ".globl __clock_gettime64",
    ".type __clock_gettime64, %function",
    "__clock_gettime64:",
    "b clock_gettime",
    ".globl __clock_nanosleep_time64",
    ".type __clock_nanosleep_time64, %function",
    "__clock_nanosleep_time64:",
    "b clock_nanosleep",
    ".globl __clock_settime64",
    ".type __clock_settime64, %function",
    "__clock_settime64:",
    "b clock_settime",
    ".globl __cnd_timedwait_time64",
    ".type __cnd_timedwait_time64, %function",
    "__cnd_timedwait_time64:",
    "b cnd_timedwait",
    ".globl __ctime64",
    ".type __ctime64, %function",
    "__ctime64:",
    "b ctime",
    ".globl __ctime64_r",
    ".type __ctime64_r, %function",
    "__ctime64_r:",
    "b ctime_r",
    ".globl __difftime64",
    ".type __difftime64, %function",
    "__difftime64:",
    "b difftime",
    ".globl __dlsym_time64",
    ".type __dlsym_time64, %function",
    "__dlsym_time64:",
    "b dlsym",
    ".globl __fstat_time64",
    ".type __fstat_time64, %function",
    "__fstat_time64:",
    "b fstat",
    ".globl __fstatat_time64",
    ".type __fstatat_time64, %function",
    "__fstatat_time64:",
    "b fstatat",
    ".globl __futimens_time64",
    ".type __futimens_time64, %function",
    "__futimens_time64:",
    "b futimens",
    ".globl __getitimer_time64",
    ".type __getitimer_time64, %function",
    "__getitimer_time64:",
    "b getitimer",
    ".globl __getrusage_time64",
    ".type __getrusage_time64, %function",
    "__getrusage_time64:",
    "b getrusage",
    ".globl __gettimeofday_time64",
    ".type __gettimeofday_time64, %function",
    "__gettimeofday_time64:",
    "b gettimeofday",
    ".globl __gmtime64",
    ".type __gmtime64, %function",
    "__gmtime64:",
    "b gmtime",
    ".globl __gmtime64_r",
    ".type __gmtime64_r, %function",
    "__gmtime64_r:",
    "b gmtime_r",
    ".globl __localtime64",
    ".type __localtime64, %function",
    "__localtime64:",
    "b localtime",
    ".globl __localtime64_r",
    ".type __localtime64_r, %function",
    "__localtime64_r:",
    "b localtime_r",
    ".globl __lstat_time64",
    ".type __lstat_time64, %function",
    "__lstat_time64:",
    "b lstat",
    ".globl __lutimes_time64",
    ".type __lutimes_time64, %function",
    "__lutimes_time64:",
    "b lutimes",
    ".globl __mktime64",
    ".type __mktime64, %function",
    "__mktime64:",
    "b mktime",
    ".globl __mtx_timedlock_time64",
    ".type __mtx_timedlock_time64, %function",
    "__mtx_timedlock_time64:",
    "b mtx_timedlock",
    ".globl __nanosleep_time64",
    ".type __nanosleep_time64, %function",
    "__nanosleep_time64:",
    "b nanosleep",
    ".globl __ppoll_time64",
    ".type __ppoll_time64, %function",
    "__ppoll_time64:",
    "b ppoll",
    ".globl __pselect_time64",
    ".type __pselect_time64, %function",
    "__pselect_time64:",
    "b pselect",
    ".globl __pthread_cond_timedwait_time64",
    ".type __pthread_cond_timedwait_time64, %function",
    "__pthread_cond_timedwait_time64:",
    "b pthread_cond_timedwait",
    ".globl __pthread_mutex_timedlock_time64",
    ".type __pthread_mutex_timedlock_time64, %function",
    "__pthread_mutex_timedlock_time64:",
    "b pthread_mutex_timedlock",
    ".globl __pthread_rwlock_timedrdlock_time64",
    ".type __pthread_rwlock_timedrdlock_time64, %function",
    "__pthread_rwlock_timedrdlock_time64:",
    "b pthread_rwlock_timedrdlock",
    ".globl __pthread_rwlock_timedwrlock_time64",
    ".type __pthread_rwlock_timedwrlock_time64, %function",
    "__pthread_rwlock_timedwrlock_time64:",
    "b pthread_rwlock_timedwrlock",
    ".globl __pthread_timedjoin_np_time64",
    ".type __pthread_timedjoin_np_time64, %function",
    "__pthread_timedjoin_np_time64:",
    "b pthread_timedjoin_np",
    ".globl __recvmmsg_time64",
    ".type __recvmmsg_time64, %function",
    "__recvmmsg_time64:",
    "b recvmmsg",
    ".globl __sched_rr_get_interval_time64",
    ".type __sched_rr_get_interval_time64, %function",
    "__sched_rr_get_interval_time64:",
    "b sched_rr_get_interval",
    ".globl __select_time64",
    ".type __select_time64, %function",
    "__select_time64:",
    "b select",
    ".globl __sem_timedwait_time64",
    ".type __sem_timedwait_time64, %function",
    "__sem_timedwait_time64:",
    "b sem_timedwait",
    ".globl __semtimedop_time64",
    ".type __semtimedop_time64, %function",
    "__semtimedop_time64:",
    "b semtimedop",
    ".globl __setitimer_time64",
    ".type __setitimer_time64, %function",
    "__setitimer_time64:",
    "b setitimer",
    ".globl __settimeofday_time64",
    ".type __settimeofday_time64, %function",
    "__settimeofday_time64:",
    "b settimeofday",
    ".globl __sigtimedwait_time64",
    ".type __sigtimedwait_time64, %function",
    "__sigtimedwait_time64:",
    "b sigtimedwait",
    ".globl __stat_time64",
    ".type __stat_time64, %function",
    "__stat_time64:",
    "b stat",
    ".globl __thrd_sleep_time64",
    ".type __thrd_sleep_time64, %function",
    "__thrd_sleep_time64:",
    "b thrd_sleep",
    ".globl __time64",
    ".type __time64, %function",
    "__time64:",
    "b time",
    ".globl __timegm_time64",
    ".type __timegm_time64, %function",
    "__timegm_time64:",
    "b timegm",
    ".globl __timerfd_gettime64",
    ".type __timerfd_gettime64, %function",
    "__timerfd_gettime64:",
    "b timerfd_gettime",
    ".globl __timerfd_settime64",
    ".type __timerfd_settime64, %function",
    "__timerfd_settime64:",
    "b timerfd_settime",
    ".globl __utime64",
    ".type __utime64, %function",
    "__utime64:",
    "b utime",
    ".globl __utimensat_time64",
    ".type __utimensat_time64, %function",
    "__utimensat_time64:",
    "b utimensat",
    ".globl __utimes_time64",
    ".type __utimes_time64, %function",
    "__utimes_time64:",
    "b utimes",
    ".globl __wait3_time64",
    ".type __wait3_time64, %function",
    "__wait3_time64:",
    "b wait3",
    ".globl __wait4_time64",
    ".type __wait4_time64, %function",
    "__wait4_time64:",
    "b wait4",
    ".globl __fpclassifyl",
    ".type __fpclassifyl, %function",
    "__fpclassifyl:",
    "b __fpclassify",
    ".globl __signbitl",
    ".type __signbitl, %function",
    "__signbitl:",
    "b __signbit",
    ".globl acoshl",
    ".type acoshl, %function",
    "acoshl:",
    "b acosh",
    ".globl acosl",
    ".type acosl, %function",
    "acosl:",
    "b acos",
    ".globl asinhl",
    ".type asinhl, %function",
    "asinhl:",
    "b asinh",
    ".globl asinl",
    ".type asinl, %function",
    "asinl:",
    "b asin",
    ".globl atan2l",
    ".type atan2l, %function",
    "atan2l:",
    "b atan2",
    ".globl atanhl",
    ".type atanhl, %function",
    "atanhl:",
    "b atanh",
    ".globl atanl",
    ".type atanl, %function",
    "atanl:",
    "b atan",
    ".globl cbrtl",
    ".type cbrtl, %function",
    "cbrtl:",
    "b cbrt",
    ".globl ceill",
    ".type ceill, %function",
    "ceill:",
    "b ceil",
    ".globl copysignl",
    ".type copysignl, %function",
    "copysignl:",
    "b copysign",
    ".globl coshl",
    ".type coshl, %function",
    "coshl:",
    "b cosh",
    ".globl cosl",
    ".type cosl, %function",
    "cosl:",
    "b cos",
    ".globl dreml",
    ".type dreml, %function",
    "dreml:",
    "b drem",
    ".globl erfcl",
    ".type erfcl, %function",
    "erfcl:",
    "b erfc",
    ".globl erfl",
    ".type erfl, %function",
    "erfl:",
    "b erf",
    ".globl exp2l",
    ".type exp2l, %function",
    "exp2l:",
    "b exp2",
    ".globl expl",
    ".type expl, %function",
    "expl:",
    "b exp",
    ".globl expm1l",
    ".type expm1l, %function",
    "expm1l:",
    "b expm1",
    ".globl fabsl",
    ".type fabsl, %function",
    "fabsl:",
    "b fabs",
    ".globl fdiml",
    ".type fdiml, %function",
    "fdiml:",
    "b fdim",
    ".globl floorl",
    ".type floorl, %function",
    "floorl:",
    "b floor",
    ".globl fmal",
    ".type fmal, %function",
    "fmal:",
    "b fma",
    ".globl fmaxl",
    ".type fmaxl, %function",
    "fmaxl:",
    "b fmax",
    ".globl fminl",
    ".type fminl, %function",
    "fminl:",
    "b fmin",
    ".globl fmodl",
    ".type fmodl, %function",
    "fmodl:",
    "b fmod",
    ".globl frexpl",
    ".type frexpl, %function",
    "frexpl:",
    "b frexp",
    ".globl hypotl",
    ".type hypotl, %function",
    "hypotl:",
    "b hypot",
    ".globl ilogbl",
    ".type ilogbl, %function",
    "ilogbl:",
    "b ilogb",
    ".globl j0l",
    ".type j0l, %function",
    "j0l:",
    "b j0",
    ".globl j1l",
    ".type j1l, %function",
    "j1l:",
    "b j1",
    ".globl jnl",
    ".type jnl, %function",
    "jnl:",
    "b jn",
    ".globl ldexpl",
    ".type ldexpl, %function",
    "ldexpl:",
    "b ldexp",
    ".globl lgammal",
    ".type lgammal, %function",
    "lgammal:",
    "b lgamma",
    ".globl lgammal_r",
    ".type lgammal_r, %function",
    "lgammal_r:",
    "b lgamma_r",
    ".globl llrintl",
    ".type llrintl, %function",
    "llrintl:",
    "b llrint",
    ".globl llroundl",
    ".type llroundl, %function",
    "llroundl:",
    "b llround",
    ".globl log10l",
    ".type log10l, %function",
    "log10l:",
    "b log10",
    ".globl log1pl",
    ".type log1pl, %function",
    "log1pl:",
    "b log1p",
    ".globl log2l",
    ".type log2l, %function",
    "log2l:",
    "b log2",
    ".globl logbl",
    ".type logbl, %function",
    "logbl:",
    "b logb",
    ".globl logl",
    ".type logl, %function",
    "logl:",
    "b log",
    ".globl lrintl",
    ".type lrintl, %function",
    "lrintl:",
    "b lrint",
    ".globl lroundl",
    ".type lroundl, %function",
    "lroundl:",
    "b lround",
    ".globl modfl",
    ".type modfl, %function",
    "modfl:",
    "b modf",
    ".globl nanl",
    ".type nanl, %function",
    "nanl:",
    "b nan",
    ".globl nearbyintl",
    ".type nearbyintl, %function",
    "nearbyintl:",
    "b nearbyint",
    ".globl nextafterl",
    ".type nextafterl, %function",
    "nextafterl:",
    "b nextafter",
    ".globl nexttoward",
    ".type nexttoward, %function",
    "nexttoward:",
    "b nextafter",
    ".globl nexttowardl",
    ".type nexttowardl, %function",
    "nexttowardl:",
    "b nextafter",
    ".globl powl",
    ".type powl, %function",
    "powl:",
    "b pow",
    ".globl remainderl",
    ".type remainderl, %function",
    "remainderl:",
    "b remainder",
    ".globl remquol",
    ".type remquol, %function",
    "remquol:",
    "b remquo",
    ".globl rintl",
    ".type rintl, %function",
    "rintl:",
    "b rint",
    ".globl roundl",
    ".type roundl, %function",
    "roundl:",
    "b round",
    ".globl scalblnl",
    ".type scalblnl, %function",
    "scalblnl:",
    "b scalbln",
    ".globl scalbnl",
    ".type scalbnl, %function",
    "scalbnl:",
    "b scalbn",
    ".globl significandl",
    ".type significandl, %function",
    "significandl:",
    "b significand",
    ".globl sinhl",
    ".type sinhl, %function",
    "sinhl:",
    "b sinh",
    ".globl sinl",
    ".type sinl, %function",
    "sinl:",
    "b sin",
    ".globl sqrtl",
    ".type sqrtl, %function",
    "sqrtl:",
    "b sqrt",
    ".globl tanhl",
    ".type tanhl, %function",
    "tanhl:",
    "b tanh",
    ".globl tanl",
    ".type tanl, %function",
    "tanl:",
    "b tan",
    ".globl tgammal",
    ".type tgammal, %function",
    "tgammal:",
    "b tgamma",
    ".globl truncl",
    ".type truncl, %function",
    "truncl:",
    "b trunc",
    ".globl y0l",
    ".type y0l, %function",
    "y0l:",
    "b y0",
    ".globl y1l",
    ".type y1l, %function",
    "y1l:",
    "b y1",
    ".globl ynl",
    ".type ynl, %function",
    "ynl:",
    "b yn",
    ".popsection",
);
