//! Variadic functions: the entry thunks that let Rust implement `printf`, and
//! the reader that takes their arguments.
//!
//! Stable Rust cannot define a C variadic function. Nor can a variadic
//! function be faked with a fixed list of parameters, as `open` can: `printf`
//! takes any number of arguments, and a `double` among them travels in a vector
//! register that an integer parameter never sees. So each variadic function the
//! library exports is a short piece of assembly, generated by [`variadic!`],
//! which does what `va_start` does in C and then calls a Rust function taking a
//! `va_list`. That Rust function is almost always the `v*` twin C already
//! defines: `printf` calls `vprintf`, `execl` would call a function taking the
//! list.
//!
//! Each architecture's calling convention defines `va_list` differently, and
//! its module says how: [`x86_64`](self) and AArch64 save the argument
//! registers and keep offsets into them, while ARMv7-A saves r0 to r3 beside
//! the stack and walks both with one pointer. What is the same everywhere is
//! [`VaList`], the reader, whose methods take the next argument of a type.
//!
//! # Reusing it
//!
//! To export a variadic C function `int f(A a, B b, ...)` whose named
//! arguments are integers or pointers:
//!
//! 1. write `unsafe extern "C" fn vf(a: A, b: B, ap: VaListArg) -> c_int`,
//!    exported under its own C name if C has one;
//! 2. inside it, make a reader with [`VaList::from_raw`] and take each
//!    argument with the method for its type;
//! 3. write `crate::va::variadic!(f, 2, vf);` at module level.
//!
//! In unit test builds the thunk is named `ferrousli_test_f` instead, so it
//! does not take the host C library's name, and a test can still call it
//! through an `extern "C"` declaration with `...`.

#[cfg(target_arch = "aarch64")]
mod aarch64;
#[cfg(target_arch = "arm")]
mod arm;
#[cfg(target_arch = "x86_64")]
mod x86_64;

#[cfg(target_arch = "aarch64")]
pub(crate) use aarch64::variadic;
#[cfg(target_arch = "aarch64")]
pub use aarch64::{LongDouble, VaListArg, VaListTag};
#[cfg(target_arch = "arm")]
pub(crate) use arm::variadic;
#[cfg(target_arch = "arm")]
pub use arm::{LongDouble, VaListArg, VaListTag};
#[cfg(target_arch = "x86_64")]
pub(crate) use x86_64::variadic;
#[cfg(target_arch = "x86_64")]
pub use x86_64::{LongDouble, VaListArg, VaListTag};

/// A copy of the list `ap`, as C's `va_copy` makes one.
///
/// # Safety
///
/// `ap` must be a live `va_list` parameter.
#[cfg(not(target_arch = "arm"))]
pub unsafe fn copy(ap: VaListArg) -> VaListTag {
    // SAFETY: the caller vouches for the list.
    unsafe { ap.read() }
}

/// A copy of the list `ap`, as C's `va_copy` makes one: on ARMv7-A the
/// parameter is the list itself.
///
/// # Safety
///
/// `ap` must be a live `va_list` parameter.
#[cfg(target_arch = "arm")]
pub unsafe fn copy(ap: VaListArg) -> VaListTag {
    ap
}

/// `tag`, as a `va_list` parameter passes it: a pointer to it, or on ARMv7-A
/// the list itself.
#[cfg(not(target_arch = "arm"))]
pub fn as_arg(tag: &mut VaListTag) -> VaListArg {
    tag
}

/// `tag`, as a `va_list` parameter passes it: a pointer to it, or on ARMv7-A
/// the list itself.
#[cfg(target_arch = "arm")]
pub fn as_arg(tag: &mut VaListTag) -> VaListArg {
    *tag
}

/// Where a reader's list lives.
#[derive(Debug)]
enum Tag<'a> {
    /// In the caller's structure, which reading advances.
    Borrowed(&'a mut VaListTag),
    /// In the reader: a `va_list` passed by value, as on ARMv7-A.
    #[cfg(target_arch = "arm")]
    Owned(VaListTag),
}

/// A reader of a `va_list`'s arguments. The methods that take an argument are
/// each architecture's.
#[derive(Debug)]
pub struct VaList<'a> {
    tag: Tag<'a>,
}

impl<'a> VaList<'a> {
    /// A reader of the list `ap`, as a `va_list` parameter arrives.
    ///
    /// # Safety
    ///
    /// `ap` must be a `va_list` that `va_start`, `va_copy` or a [`variadic!`]
    /// thunk filled, whose arguments are still live, and that nothing else
    /// uses while the reader does.
    #[cfg(not(target_arch = "arm"))]
    pub unsafe fn from_raw(ap: VaListArg) -> Self {
        // SAFETY: the caller vouches for the structure and its exclusive use.
        let tag = unsafe { &mut *ap };
        Self {
            tag: Tag::Borrowed(tag),
        }
    }

    /// A reader of the list `ap`, as a `va_list` parameter arrives.
    ///
    /// # Safety
    ///
    /// `ap` must be a `va_list` that `va_start`, `va_copy` or a [`variadic!`]
    /// thunk filled, whose arguments are still live.
    #[cfg(target_arch = "arm")]
    pub unsafe fn from_raw(ap: VaListArg) -> Self {
        Self {
            tag: Tag::Owned(ap),
        }
    }

    /// A reader of `tag`, a copy the caller keeps.
    pub fn from_tag(tag: &'a mut VaListTag) -> Self {
        Self {
            tag: Tag::Borrowed(tag),
        }
    }

    /// A copy of the list as it stands, as `va_copy` makes.
    pub fn copy(&self) -> VaListTag {
        match &self.tag {
            Tag::Borrowed(tag) => **tag,
            #[cfg(target_arch = "arm")]
            Tag::Owned(tag) => *tag,
        }
    }

    /// The list, to advance.
    fn tag(&mut self) -> &mut VaListTag {
        match &mut self.tag {
            Tag::Borrowed(tag) => tag,
            #[cfg(target_arch = "arm")]
            Tag::Owned(tag) => tag,
        }
    }

    /// The next argument, which is an `int` or narrower.
    ///
    /// # Safety
    ///
    /// The next argument must be an `int`, or narrower and promoted to one.
    pub unsafe fn next_int(&mut self) -> i32 {
        // SAFETY: the caller vouches for the argument's type.
        let word = unsafe { self.next_word() };
        word as i32
    }

    /// The next argument, which is a pointer.
    ///
    /// # Safety
    ///
    /// The next argument must be a pointer.
    pub unsafe fn next_ptr<T>(&mut self) -> *mut T {
        // SAFETY: the caller vouches for the argument's type.
        let word = unsafe { self.next_word() };
        core::ptr::with_exposed_provenance_mut(word as usize)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use core::ffi::{c_char, c_int};

    /// Reads one argument per byte of `kinds` (`i` an `int`, `w` a
    /// `long long`, `d` a `double`, `p` a pointer) into `out`, as 64-bit
    /// words.
    unsafe extern "C" fn probe(kinds: *const c_char, out: *mut u64, ap: VaListArg) -> c_int {
        // SAFETY: the thunk passes the list it built.
        let mut list = unsafe { VaList::from_raw(ap) };
        let mut i = 0;
        loop {
            // SAFETY: the test passes a NUL-terminated string.
            let kind = unsafe { kinds.wrapping_add(i).read() } as u8;
            let value = match kind {
                // SAFETY: the kind names the next argument's type.
                b'i' => i64::from(unsafe { list.next_int() }) as u64,
                // SAFETY: as above.
                b'w' => unsafe { list.next_wide() },
                // SAFETY: as above.
                b'p' => unsafe { list.next_ptr::<u8>() }.addr() as u64,
                // SAFETY: as above.
                b'd' => unsafe { list.next_double() }.to_bits(),
                _ => return i as c_int,
            };
            // SAFETY: the test gives room for every kind.
            unsafe { out.wrapping_add(i).write(value) };
            i += 1;
        }
    }

    variadic!(va_probe, 2, probe);

    unsafe extern "C" {
        #[link_name = "ferrousli_test_va_probe"]
        fn va_probe(kinds: *const c_char, out: *mut u64, ...) -> c_int;
    }

    #[test]
    fn arguments_of_every_class_come_back_in_order_past_the_registers() {
        let mut out = [0_u64; 25];
        let marker = 0x9abc_def0_usize;
        // SAFETY: each argument matches its kind, and `out` has room.
        let count = unsafe {
            va_probe(
                c"iidwdidwdidwdiddddddpdwii".as_ptr(),
                out.as_mut_ptr(),
                -1_i32,
                2_i32,
                0.5_f64,
                -3_i64,
                1.25_f64,
                4_i32,
                2.5_f64,
                5_i64,
                3.75_f64,
                6_i32,
                -0.0_f64,
                i64::MIN,
                1e300_f64,
                7_i32,
                5.0_f64,
                6.0_f64,
                7.0_f64,
                8.0_f64,
                9.0_f64,
                10.0_f64,
                core::ptr::without_provenance::<u8>(marker),
                11.0_f64,
                i64::MAX,
                8_i32,
                9_i32,
            )
        };
        assert_eq!(count, 25);
        let expect: [u64; 25] = [
            -1_i64 as u64,
            2,
            0.5_f64.to_bits(),
            -3_i64 as u64,
            1.25_f64.to_bits(),
            4,
            2.5_f64.to_bits(),
            5,
            3.75_f64.to_bits(),
            6,
            (-0.0_f64).to_bits(),
            i64::MIN as u64,
            1e300_f64.to_bits(),
            7,
            5.0_f64.to_bits(),
            6.0_f64.to_bits(),
            7.0_f64.to_bits(),
            8.0_f64.to_bits(),
            9.0_f64.to_bits(),
            10.0_f64.to_bits(),
            marker as u64,
            11.0_f64.to_bits(),
            i64::MAX as u64,
            8,
            9,
        ];
        assert_eq!(out, expect);
    }
}
